name: Build Blockiau
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all # This is needed to create a new git tag

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - name: Create git tag if package.json is newer than latest git tag
        run: |
          if [ "$(git tag --points-at HEAD)" = "" ] || [ "$(git describe --tags --abbrev=0)" != "$(git tag --points-at HEAD)" ]; then
            echo "Creating new git tag"
            git tag v$(node -p "require('./package.json').version")
            git push origin v$(node -p "require('./package.json').version")
          else
            echo "No new git tag needed"
          fi
