name: PR request Blockiau
on:
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run format
      - run: npm run build
      - name: Check if package.json version is listed in git tags
        run: |
          git fetch --tags
          VERSION=$(node -p "require('./package.json').version")
          git show-ref --tags --verify --quiet -- "refs/tags/v$VERSION" && echo "Version v$VERSION exists" && exit 1 || echo "Version v$VERSION allowed"
